### ISSUE TITLE
Bot

### ISSUE THREAD

**Issue by ghost** [DefaltSimon/Nano#1]
Hi @DefaltSimon 

Loving your bot `nano` creating my own bot for a game of mine.

Was wondering can I use some of your source? If I can what credits would you like me to provide for you?

**Comment by simongoricar** [comment]
Hey @di48l069 

You're more than welcome to use the source for your project! About the credits; it would be awesome if you could mention this repo or me (a link would be nice :wink: ) somewhere in your project.

By the way, Nano is licensed under MIT, so be sure to include a license in your project as well.

**Comment by ghost** [comment]
Thanks bud keep up the good work
