### ISSUE TITLE
You may want to set a max number of dice on !dice

### ISSUE THREAD

**Issue by AMScaglione** [DefaltSimon/Nano#4]
So I added nano to my server, and being a server populated a few CS people, we immediately went a bit ham testing it out. I tried to roll 2147483647d2147483647 to see how it handled max int. I may have crashed the bot, its been offline since I tried. Anyways you may want to limit the number of dice you can roll to maybe 1000 or so.

**Comment by simongoricar** [comment]
Nice find!

I'll limit the amount of dices to 1000 and its sides to 1000.
The max amout of dices to sum will also now be 75.

Quick math for the highest sum possible: 1000*1000 * 75 = 75,000,000 which should not be a problem.

**Comment by simongoricar** [comment]
Actually: 50 will do (75 can be so long, that Nano can't even send the message)
